# Generated by Django 2.2.6 on 2019-10-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regular_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('small', models.FloatField()),
                ('large', models.FloatField()),
                ('toppings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sicilian_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('small', models.FloatField()),
                ('large', models.FloatField()),
                ('items', models.IntegerField(default=0)),
            ],
        ),
    ]
