# Generated by Django 2.2.6 on 2019-10-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0012_auto_20191027_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
