# Generated by Django 2.2.6 on 2019-10-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20191005_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='large',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='small',
        ),
    ]
