# Generated by Django 2.2.6 on 2019-10-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
